/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kenji' at '17/04/15 9:23' with Gradle 2.14.1
 *
 * @author kenji, @date 17/04/15 9:23
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
